# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0a51d118b5a1085c9697438c35c9a3a38478e5fd338379e1453a6982a5e5c76427c0ae565ec732cffe56a9de80fca43cd31c4b60720eabf8f21b09a4460b66e6

test:
  secret_key_base: af977501063ad2de64f520ef8ebfa53be23a96d5e1dc9d9036d37a74591b3623499e63fedcd6158b5196054631054022b3597674e43f04579350b9b2cbf3a4a0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
